### PR TITLE
Use getsourcecode endpoint from etherscan api instead of anyabi+ proxy detection logic 

### LINKED ISSUE #141: Problems with anyabi + two stepped detection
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/BuidlGuidl/abi.ninja/issues)

### Current Behavior

Currently when a user types in a contract address, the app:
1. checks anyabi for an abi
2. if it can't find it, it checks etherscan
3. if it still cannot find it, the app changes the view to heimdall + manual abi view

This takes a lot of time and on top of this, anyabi now returns the same abi for any non-existant contract on sepolia.

example:
try this address for sepolia: 0x1111111111111111111111111111111111111111

https://github.com/user-attachments/assets/0289e887-70f7-4500-b6e2-9942b919766f

### Expected Behavior

I believe that we can have this much better with a very basic custom backend for abi.ninja that would:
1. return abis from etherscan
2. detect proxies 
3. decompiles contracts
4. lets the caller know if contracts are proxies and/or decompiled

### Steps To Reproduce

Try this link:
https://abi.ninja/0x1111111111111111111111111111111111111111/11155111

### Anything else?

Here is a simple backend that does what we want:

https://github.com/portdeveloper/get-abi-2000

with this, we can safely remove the checks for the proxy contracts on the frontend as well as trying to get abis from two sources.

**So, please let me know what you think below!**

### PR DESCRIPTION
**Pull request by portdeveloper**
### This PR 
-> Uses getsourcecode api, which can be found here: https://docs.etherscan.io/api-endpoints/contracts 
-> Removes the use of anyabi and proxy detection logic

### To-Do 

- [x] Need to update the tests accordingly 
(We probably need to add all those env vars to github actions for the tests to work, and i don't have access to that)

## Related Issues

Fixes #141

### CODE REVIEW

**Review by Pabl0cks — COMMENTED** [review]
AWESOME job @portdeveloper!!

Tested nicely with different use cases and is working nicely! And implementation contracts are working great now.

Just missing to verify one use case (custom chains). Tried using your custom chain example and is not working for me:

> parex chain details:
> chainId: 322202
> rpc: https://mainnet-rpc.parex.network
> verified contract: 0x6058518142C6AD506530F5A62dCc58050bf6fC28
> block explorer: https://scan.parex.network/

**Comment by portdeveloper** [comment]
@Pabl0cks Thanks for the review!

Unfortunately, parex network is down and Shiv found another chain:

`  it("should add Viction as a custom chain and interact with a contract by submitting an ABI manually", () => {
    cy.visit("http://localhost:3000");
    cy.selectNetwork("Add custom chain");
    cy.get("#add-custom-chain-modal").should("be.visible");
    cy.addCustomChain({
      id: "88",
      name: "Viction",
      nativeCurrencyName: "VIC",
      nativeCurrencySymbol: "VIC",
      nativeCurrencyDecimals: "18",
      rpcUrl: "https://rpc.viction.xyz",
      blockExplorer: "https://tomoscan.io/",
    });
    cy.get("#react-select-container").should("contain", "Viction");
    cy.get('input[placeholder="Contract address"]').type("0x381B31409e4D220919B2cFF012ED94d70135A59e");
    cy.fixture("viction_abi").then(victionABI => {
      cy.importABI(JSON.stringify(victionABI));
    });
    cy.url().should("include", "/0x381B31409e4D220919B2cFF012ED94d70135A59e/88");
    cy.get(".loading-spinner", { timeout: 10000 }).should("not.exist");
    cy.interactWithMethod("balanceOf", "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045");
  });`

And if you use Viction, you successfully reach addressAbi tab and import an ABI manually and reach the interaction page.

**Comment by technophile-04** [comment]
Ohh don't know how I missed this PR, will try it over weekend 🙌

**Comment by Pabl0cks** [comment]
> And if you use Viction, you successfully reach addressAbi tab and import an ABI manually and reach the interaction page.

TYSM! Approving the PR now 🙌

**Review by Pabl0cks — APPROVED** [review]

File: packages/nextjs/utils/abi.ts [hunk 1]
```diff
@@ -1,41 +1,88 @@
...
+  if (sourceCodeData.status !== "1" || !sourceCodeData.result || sourceCodeData.result.length === 0) {
+    console.error("Error fetching source code from Etherscan:", sourceCodeData);
+    throw new Error("Failed to fetch source code from Etherscan");
   }
+
+  const contractData = sourceCodeData.result[0];
+  const implementation = contractData.Implementation || null;
+
+  // If there's an implementation address, make a second call to get its ABI
+  if (implementation && implementation !== "0x0000000000000000000000000000000000000000") {
```
Comment (technophile-04) [inline packages/nextjs/utils/abi.ts:65]: NIT: I think maybe we could have https://github.com/scaffold-eth/scaffold-eth-2/blob/e6b84bf3e0a2eba7ae3d0ed47d66198aba1a3968/packages/nextjs/utils/scaffold-eth/common.ts#L7 from SE-2 since we are checking it at different places

**Review by technophile-04 — COMMENTED** [review]
Tysm @portdeveloper!! Great find on getsourcode enpoint! removes a lot of burden and network request to check for proxies! Just tested it out looks good! Added a couple of small comments 

--- 

Regarding GH actions tests now if someone outsider makes a PR to abi.ninja they would always fails since their fork/branch won't be able to access our variables. 

A manual solution for now would be we(reviewer) run `yarn cypress:run` locally  and see if that PR passes the test before merging. I think we had chat about it in TG and also tried digging about it https://github.com/technophile-04/abininja-fork/commit/5a2a48b4b1dd1d9613b6dff7f1e1126eaebab00f but it seems to doesn't work but yeah in long run it would be great if we get it solved not at all top-priority though

**Comment by technophile-04** [comment]
Just pushed a couple of commits(hacky) to fix the GH action, the problem seems even after adding those variables to github secrets they were not getting picked by nextjs so added a step where we echo `.env.local` inside `packages/nexjts` not the solution I am proud off :/ but yeah I think we should solve this too while tinkering with second part of https://github.com/BuidlGuidl/abi.ninja/pull/157#pullrequestreview-2336550053

**Comment by portdeveloper** [comment]
@technophile-04 thanks for you feedback, fixed!

also about the automated tests problem, i wonder if playwright is easier to configure?

**Review by technophile-04 — APPROVED** [review]
Tysm @portdeveloper !!
