### PR TITLE
Fix open zeppelin proxy detection

### LINKED ISSUE #154: bug: Unable to detect implementation address of proxy contracts such as USDC contract on mainnet
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/BuidlGuidl/abi.ninja/issues)

### Current Behavior

We are not able to detect open zeppelin proxy contracts because the implementation slot is commented out and there is no logic corresponding to that slot.

Please see: https://abi.ninja/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48/1

### Expected Behavior

We should be able to correctly detect the imlementation address and show the correct ABI for any contract implemented within OZ proxy contract standards.

### Steps To Reproduce

1. Go to abi.ninja
2. On Ethereum, type in this address 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
3. Click load contract

OR

1. Go to the following address: https://abi.ninja/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48/1

### Anything else?

Will open a PR with a fix shortly!

### PR DESCRIPTION
**Pull request by portdeveloper**
## Description

This PR adds support for detecting OpenZeppelin proxies by uncommenting and implementing the OpenZeppelin implementation slot detection logic in the `detectProxyTarget` function.

Changes made:
1. Uncommented the `OPEN_ZEPPELIN_IMPLEMENTATION_SLOT` constant.
2. Added a new `detectUsingOpenZeppelinSlot` function to check for OpenZeppelin proxies.
3. Included the new detection method in the primary detection methods array.

## Additional Information

- [x] I have read the [contributing docs](https://github.com/BuidlGuidl/abi.ninja/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [x] This is not a duplicate of any [existing pull request](https://github.com/BuidlGuidl/abi.ninja/pulls)

## Related Issues

Fixes #154 

Your ENS/address: portdev.eth

### CODE REVIEW

**Review by Pabl0cks — COMMENTED** [review]
Nice catch! Thanks for tackling it so fast.

Now it detects the proxy nicely for USDC in mainnet, but I got a question there.

In [etherscan read proxy](https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48#readProxyContract) you can read the balance of an account nicely (0x4bBB30C26AEB7ABDBFb937D5C206CC29f9706323) but not in [abi ninja](https://abi-ninja-v2-git-fix-open-zeppelin-impl-detection-buidlguidldao.vercel.app/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48/1?methods=balanceOf)

It seems like if we are querying directly the implementation address, like [etherscan does here](https://etherscan.io/address/0x43506849d7c04f9138d1a2050bbf3a0c054402dd#readContract)

Also if you open [USDC mainnet in abi ninja](https://abi-ninja-v2-git-fix-open-zeppelin-impl-detection-buidlguidldao.vercel.app/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48/1) and select a method, the URL reloads to the [implementation address](https://abi-ninja-v2-git-fix-open-zeppelin-impl-detection-buidlguidldao.vercel.app/0x43506849d7c04f9138d1a2050bbf3a0c054402dd/1?methods=balanceOf)

**Comment by portdeveloper** [comment]
@Pabl0cks thanks for the feedback!
I have just checked the main branch and this problem exists there too. 

Merging in https://github.com/BuidlGuidl/abi.ninja/tree/feat/getsourcecode fixes that problem as well as improving the overall app.

Here is a deployment link for that branch if you'd like to test:
https://abi-ninja-v2-git-feat-getsourcecode-buidlguidldao.vercel.app/


My suggestion here would be, since the problem exists on prod deployment as well, is either:
-> merge this, i open a new pr for getsourcecode, merge that
-> I close this and make getsourcecode + this as one new pr


How do those options sound? Happy to hear any ideas!

File: packages/nextjs/utils/abi-ninja/proxyContracts.ts [hunk 1]
```diff
@@ -89,7 +89,24 @@ export const detectProxyTarget = async (proxyAddress: Address, client: UsePublic
...
-  const detectionMethods = [detectUsingBytecode, detectUsingEIP1967LogicSlot, detectUsingEIP1967BeaconSlot];
+  const detectUsingOpenZeppelinSlot = async () => {
+    const implementationAddr = await client.getStorageAt({
+      address: proxyAddress,
+      slot: OPEN_ZEPPELIN_IMPLEMENTATION_SLOT,
+    });
+    const resolvedAddress = readAddress(implementationAddr);
+    if (resolvedAddress === "0x" + "0".repeat(40)) {
+      throw new Error("Zero address in OpenZeppelin implementation slot");
+    }
```
Comment (technophile-04) [inline packages/nextjs/utils/abi-ninja/proxyContracts.ts:100]: Ohh I think this check is redundant since `readAddress` already checks for zero address and throw's error, so we could remove this?

**Review by technophile-04 — APPROVED** [review]
I think the changes makes sense, btw @portdeveloper do you remember why we commented that OZ slot? I don't remember any discussion on that :/. 

Nevertheless I think we can merge this just added a small comment and create a new PR for `getSourceCode` branch

**Review by Pabl0cks — APPROVED** [review]
Ok! I also agree is a good idea to merge this and then test nicely the `getsourcecode` PR and merge it when looks good.

I will document the issue just to make sure we verify it in the new PR 🙏

**Comment by portdeveloper** [comment]
I don't remember the exact reason why we commented it out (might be related to when we separated the logic)
But when we merge getsourcecode PR we will remove these all!
